# Generated by Django 5.2.13 on 2026-05-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeAdminLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
